### ISSUE TITLE
generate_datas.py有一处错误？

### ISSUE THREAD

**Issue by zhaoling1988** [lipengfei-558/hmm_ner_organization#1]
def generate_emit_probability(initial_freq)函数中，
result.append([tmp_list[0],observed_state,float(tags_and_freq[1])/initial_freq[tmp_list[0]]])  应该改为
result.append([tmp_list[0],observed_state,float(tmp_list[1])/initial_freq[tmp_list[0]]])  吧？

**Comment by lipengfei-558** [comment]
感谢指正，已修改 @zhaoling1988

**Comment by lidianxiang** [comment]
按照一楼的指定后，运行generate-datas.py文件，会报错：
generated ./data/initial_vector.txt
generated ./data/transition_probability.txt
Traceback (most recent call last):
  File "generate_datas.py", line 100, in <module>
    generate_emit_probability(get_initial_freq())
  File "generate_datas.py", line 71, in generate_emit_probability
    result.append([tmp_list[0], observed_state, float(tmp_list[1]) / initial_freq[tmp_list[0]]])
ValueError: could not convert string to float: 'W'

**Comment by uestcwm** [comment]
> 按照一楼的指定后，运行generate-datas.py文件，会报错：
> generated ./data/initial_vector.txt
> generated ./data/transition_probability.txt
> Traceback (most recent call last):
> File "generate_datas.py", line 100, in 
> generate_emit_probability(get_initial_freq())
> File "generate_datas.py", line 71, in generate_emit_probability
> result.append([tmp_list[0], observed_state, float(tmp_list[1]) / initial_freq[tmp_list[0]]])
> ValueError: could not convert string to float: 'W'

请问你解决了吗？我也报这个错

**Comment by uestcwm** [comment]
错误解决方案：按照第一义issue把txt中空格行去掉
