### ISSUE TITLE
generate_datas.py中有一个错误

### ISSUE THREAD

**Issue by ghost** [lipengfei-558/hmm_ner_organization#2]
python generate_datas.py
Traceback (most recent call last):
  File "generate_datas.py", line 91, in <module>
    genertate_initial_vector(hidden_states)
  File "generate_datas.py", line 20, in genertate_initial_vector
    the_hidden_states[tmp_list[0]] += eval(tmp_list[1])
KeyError: '2'

**Comment by canwushuang** [comment]
具体这个问题来源于“空格”的错误，tags_and_freq = line.strip().split(" ")[1:]，具体看nt.txt文本，55行是空格的统计，所以会报错。删除这行可以运行。
    with open("./data/nt.txt",'r',encoding='utf-8') as nrfile:
        all_data = nrfile.readlines()
        _**all_data.remove(all_data[54])**_

**Comment by canwushuang** [comment]
>           python generate_datas.py
> Traceback (most recent call last):
> File "generate_datas.py", line 91, in 
> genertate_initial_vector(hidden_states)
> File "generate_datas.py", line 20, in genertate_initial_vector
> the_hidden_states[tmp_list[0]] += eval(tmp_list[1])
> KeyError: '2'

的统计，所以会报错。删除这行可以运行。
with open("./data/nt.txt",'r',encoding='utf-8') as nrfile:
all_data = nrfile.readlines()
all_data.remove(all_data[54])

**Comment by canwushuang** [comment]
nt.txt第55行是空格统计，“**tags_and_freq = line.strip().split(" ")[1:]**”，这个代码切割出错。
解决办法是
with open("./data/nt.txt",'r',encoding='utf-8') as nrfile:
all_data = nrfile.readlines()
**_all_data.remove(all_data[54])_**

**Comment by nizinizi** [comment]
加了这行：all_data.remove(all_data[54])没有解决问题。请问还有其他解决办法吗？
